services:
  mongo:
    image: mongo:7.0
    container_name: parking-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - parking-net

  backend:
    image: cr.yandex/crpm5i3fj81cq0ka0o72/backend:latest
    container_name: parking-backend
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - PORT=${PORT}
    ports:
      - "5005:5005"
    networks:
      - parking-net
    restart: unless-stopped

  frontend:
    image: cr.yandex/crpm5i3fj81cq0ka0o72/frontend:latest
    container_name: parking-frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - parking-net
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  parking-net:
    driver: bridge

