apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
  labels:
    app: backend
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- $mongoUser := .Values.mongodb.auth.rootUser | default "admin" }}
  {{- $mongoPass := .Values.mongodb.auth.rootPassword | default "changeme" }}
  {{- $mongoDb := .Values.mongodb.auth.database | default "parking" }}
  {{- $mongoHost := printf "%s-mongodb" .Release.Name }}
  {{- $mongoPort := .Values.mongodb.service.port | default 27017 | toString }}
  MONGO_URI: {{ printf "mongodb://%s:%s@%s:%s/%s?authSource=admin" $mongoUser $mongoPass $mongoHost $mongoPort $mongoDb | b64enc | quote }}
  MONGO_DB: {{ $mongoDb | b64enc | quote }}
  MONGO_HOST: {{ $mongoHost | b64enc | quote }}
  MONGO_PORT: {{ $mongoPort | b64enc | quote }}
