global:
  imageRegistry: cr.yandex/crpm5i3fj81cq0ka0o72
  environment: production
backend:
  image: backend:975865ec0b7a4abf9e5b53d57424de21fd769784
  replicas: 1
  port: 5005
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  env:
    MONGO_DB: parking
    PORT: "5005"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 15
  metrics:
    enabled: true
    path: /metrics
    port: 5005
frontend:
  image: frontend:975865ec0b7a4abf9e5b53d57424de21fd769784
  replicas: 1
  serviceType: LoadBalancer
  port: 8080
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
mongodb:
  enabled: true
  image:
    registry: cr.yandex/crpm5i3fj81cq0ka0o72
    repository: mongodb-community
    tag: "latest"
    pullPolicy: Always
  auth:
    enabled: true
    existingSecret: parking-mongo-secret
    rootUser: admin
    database: parking
    usernames: [user1]
    passwords: [user1]
    databases: [parking]
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "yc-network-hdd"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  service:
    type: ClusterIP
    port: 27017
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
  podSecurityContext:
    fsGroup: 999
    runAsNonRoot: true
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
